### ISSUE TITLE
Ticking/checking "RTL" on test pages screws up layout

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit-site#10]
Ticking the "RTL" box on this page screws up the layout:

https://getuikit.com/assets/uikit/tests/index.html

It briefly shows up with the boxes right-aligned, then it looks like all the CSS formatting is removed (including columns etc.), and you get a long bullet list of unformatted content, right-aligned.

**Comment by janschoenherr** [comment]
We've removed the RTL feature for now. It'll be added again, once it's ready.
