### ISSUE TITLE
themes.json fetched with synchronous request

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit-site#11]
The JS console in Chrome gives this warning on the test pages site:

test.js:16 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

The line is:

`request.open('GET', '../themes.json', false);`

(Not a big deal, but I figured I would report it..)

**Comment by janschoenherr** [comment]
That is currently "by design" ;-)
