### ISSUE TITLE
Slideshow: Infinite Scrolling, wrong code

### ISSUE THREAD

**Issue by lareusmedia** [uikit/uikit-site#111]
Use:
`<div uk-slideshow="infinite: true">...</div>`

instead of:
`<div uk-slideshow="finite: true">...</div>`

**Comment by saschadube** [comment]
The option is called `finite` and it is set to `false` by default. Which line of text do you think is wrong in the docs?

**Comment by lareusmedia** [comment]
Using `<div uk-slideshow="finite: true">...</div>` doesnt work in my Slideshow... Its not infinite with 2 Slides.

So i tried `<div uk-slideshow="infinite: true">...</div>` and TADAAAA... it worked!

**Comment by ccarignan** [comment]
Looks like you have it backwards.

 `finite: true` disables infinite scrolling, so it works as expected. The default value `finite: false` enables infinite scrolling.

Providing `infinite: true` only worked because `infinite` is not a valid option, so it defaults to `finite: false`.
