### ISSUE TITLE
"npm install" issue on Windows

### ISSUE THREAD

**Issue by roelpaulo** [uikit/uikit-site#117]
It seems to be complaining about the operating system and some vue requirements. npm-debug.log is attached.
[npm-debug.log](https://github.com/uikit/uikit-site/files/1714058/npm-debug.log)

**Comment by Mu9tafa-Online** [comment]
I Tried On Windows / Linux, No Luck Until Now :(

**Comment by webitproff** [comment]
хоть монитор разбивай, не могу поставить и всё!

**Comment by dasdeck** [comment]
fixed in:
e63934beec8f8a6c6f71ca2941f3ad0278f992a3

**Comment by roelpaulo** [comment]
I have commented on your commit @dasdeck :)
