### ISSUE TITLE
uikit-site v3. how to install on owner local or virtual hosting?

### ISSUE THREAD

**Issue by webitproff** [uikit/uikit-site#119]
please, I've already spent an empty two days with node / npm / bower, please make a video tutorial on installing the local offline documentation of the site or give free access to the local archive copy of such a site. this is very useful for many, who are just starting to learn UIKit3.
---
or plase share copy of carrent working arhive site with documentation UIKIT3

**Comment by Alymbek** [comment]
right now (27.02.2018) some problem with offline installation...

in general you can use this manual - [https://github.com/uikit/uikit-site/issues/104](https://github.com/uikit/uikit-site/issues/104)

**Comment by Alymbek** [comment]
pls, check this #152 
you can close, if ok
