### ISSUE TITLE
incorrect installation of the offline version

### ISSUE THREAD

**Issue by webitproff** [uikit/uikit-site#121]
Developers, please check the correct installation of the offline version of the documentation from this repository https://github.com/uikit/uikit-site. Repeatedly I take all the steps according to the instructions, and at the end I get a blank page

**Comment by Alymbek** [comment]
still problem with uikit installation, see [ https://github.com/uikit/uikit-site/issues/119](https://github.com/uikit/uikit-site/issues/119)

**Comment by Alymbek** [comment]
pls, check this #152
