### ISSUE TITLE
Tiny typo: Missing a dot '.' in front of a classname + Duplicated id in for the anchor heading

### ISSUE THREAD

**Issue by hrvojegolcic** [uikit/uikit-site#164]
Assumingly there is a dot missing in front of a classnames: "uk-margin-auto" for each of the responsive viewports on the page https://getuikit.com/docs/margin

![image](https://user-images.githubusercontent.com/6906827/59198018-057c5b00-8b93-11e9-87e8-bf94b9912ab1.png)

Additionally, the link with a "responsive" anchor in the URL would not work either since there are two headings with the id "#responsive" on that page. e.g. https://getuikit.com/docs/margin#responsive will open only the first heading "Responsive", not the second one which I wanted to post for this issue.

**Comment by saschadube** [comment]
Thanks! I fixed it in the develop branch. https://github.com/uikit/uikit-site/commit/946774c73da101e9d201f04b387414db1cc4851e

**Comment by hrvojegolcic** [comment]
Hey cool!
Just want to point out that there was another issue if it was foreseen in the upper post: 
> there are two headings with the id "#responsive" on that page. e.g. https://getuikit.com/docs/margin#responsive will open only the first heading "Responsive", not the second one which I wanted to post for this issue.

Also it's not valid to have two elements with same id in HTML
