### ISSUE TITLE
Invalid CDN links

### ISSUE THREAD

**Issue by jirkavrba** [uikit/uikit-site#180]
Hello, I just wanted to point out that CDN links provided within your documentation on the [Installation](https://getuikit.com/docs/installation) page points to cdnjs with `[uikit-version]` inserted into the link.
However latest release of uikit is 3.2.1 and on cdnjs there the latest version is 3.2.0 and therefore the provided code snippet doesn't work as the cdnjs returns HTTP 404.

**Comment by janschoenherr** [comment]
Thanks, we've switched to jsdelivr for now.
