### ISSUE TITLE
Links are broken for both uikit-site-master and uikit-site-dev

### ISSUE THREAD

**Issue by kayleeDeLucca** [uikit/uikit-site#59]
I can run the repos from both branches, but all links are broken and/or I get 404s.

Tried editing package.json "compile-less" as per previous issue, but to no avail:
"compile-less": "mkdir css && lessc less/theme.less > css/theme.css --relative-urls --rootpath=../less/ -x"

Am I missing something? Thanks for any pointers.

**Comment by florianletsch** [comment]
Does the front page render completely when you access it in your browser?

By default, the URLs are setup for Apache (note the `.htaccess` file). What server setup do you have?

**Comment by kayleeDeLucca** [comment]
My bad - the server wasn't done synchronizing. All good now!
