### ISSUE TITLE
Docs should link to test pages

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit-site#6]
The new 3.0 docs don't have a link to the tests in the navbar, but the tests are a pretty good high-density way of viewing the capabilities of UIkit.

To give more visibility to the tests, it would be great if the tests could be linked to directly from the docs navbar, and/or if each section in the docs could link to the relevant section in the tests. One example where there is a cross-link is https://getuikit.com/assets/uikit/tests/index.html .

**Comment by florianletsch** [comment]
Yes, the tests are a good way to see how to use a component, and have been neglected in the old docs. However, in the new docs we link to every test directly from the according component. Have you seen this already?

![image](https://cloud.githubusercontent.com/assets/1116784/21809675/10e0eeb2-d749-11e6-84b8-6a731402a594.png)

**Comment by lukehutch** [comment]
Oh, I totally missed that link! Thanks!
