### ISSUE TITLE
how to run @ ubuntu

### ISSUE THREAD

**Issue by balagpy** [uikit/uikit-site#60]
Thow to run @ ubuntu -- the UIkit documentation and website

**Comment by florianletsch** [comment]
Install a webserver like apache and place the uikit-site folder in the document root, e.g. `/var/www/html/uikit-site` for Apache. 

Make sure you have node and npm installed (just google how to do it for your ubuntu version).

Then run the commands from the Readme  in this repo.

And then open your browser on something like `http//localhost/uikit-site`

**Comment by balagpy** [comment]
@florianletsch  Thank you for great help :-) . I successfully install and ruining in localhost.

How to run in live servers. i have a cpanel, ( linux server) is it possible to install node and npm. or any special hosting required? 

Thank you lot. :-)

**Comment by florianletsch** [comment]
If you want to run the node files online you will need ssh access and a way to run npm on the server.

However, you could also run these scripts locally and then upload the compiled JS to your server. (you don't even need to upload the node_modules folder which is too damn large anyway). The JS runs in the browser, your server just needs to serve static files, so it should run on any hosting environment.

**Comment by rrsilaya** [comment]
Instead of moving the site to `/var/www/html` you can just run python's built-in HTTP server. Just go to the repository folder and run `python3 -m http.server` (in Python 3) or `python -m SimpleHTTPServer` then open your browser to `localhost:8000`.
