### ISSUE TITLE
How to remove box-shadow from card?  

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit-site#72]
Referring to:

https://getuikit.com/docs/utility#box-shadow

And merging with the logic of:

    .uk-padding-remove

I tried this:

    .uk-box-shadow-remove

But that doesn't remove box shadow.  

Box shadow is not defined in `card.less`:

I can remove it like this in `my_theme.less`, but not ideal:  

    // card box-shadow mixin - overrides card.less
    .hook-card() { box-shadow: none !important; }

**HTML**

    <div class="uk-width-1-3">
    <div class="uk-card uk-card-secondary uk-card-body uk-light">1-3</div>
    </div>

**Comment by florianletsch** [comment]
Just use the `uk-card` class and remove all modifier classes, like `uk-card-default` or `uk-card-secondary`.

Example: https://codepen.io/anon/pen/oeZGpG

**Comment by florianletsch** [comment]
Also, this issue should probably belong to https://github.com/uikit/uikit

Closing this for now. If my previous answer doesn't solve the issue, please open an issue in that repository.
