### ISSUE TITLE
How to run documentation on browser

### ISSUE THREAD

**Issue by Ludwigromanam** [uikit/uikit-site#73]
Hi all,
This is not an issue. I just need to know how to run the local server to view docs on browser.
I have googled and read different blogs but none of them really help.

If someone has been able to run this documentation offline or locally: https://github.com/uikit/uikit-site, please help me find out how to do so.

Thanks !

**Comment by Intiligent** [comment]
Readme has instruction.

1. Clone the repository
create folder, for example uikit-site.loc
in terminal move to this folder and execute `https://github.com/uikit/uikit-site.git .`

2. `npm install` to fetch all dependencies

3. `npm run setup` to compile all resources

4. After install need create domain `uikit-site.loc` in your local server.
(MAMP - for mac, OpenServer - for Windows. in my mind its more convinion)

5. Open in browser address `uikit-site.loc`

**Comment by Ludwigromanam** [comment]
Thanks for helping me out !
